config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations",
                           sessions: "users/sessions"}

  ### Registered users
  authenticated :user do
    root to: "customer/dashboard#index", as: :authenticated_root
  end
  
  scope :users, module: "users" do
    resource :profiles, only: %i[edit update], as: :profile
    delete "identities", to: "identities#destroy"
  end

  ### Admins
  namespace :admin do
    get "/", to: "dashboard#index", as: :dashboard

    resources :users, except: [:new, :create] do
      # roles
      delete "/roles/:role_name", to: "roles#destroy", as: :role
      post "/roles/", to: "roles#create", as: :add_role

      # bans
      post "/ban", to: "bans#create", as: :create_ban
      delete "/ban", to: "bans#destroy", as: :remove_ban

      # pretending
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection

      resources :login_activities, only: [:index, :show], shallow: true
    end
  end

  authenticate :user, ->(u) { u.is_admin? } do
    mount GoodJob::Engine, at: "good_job"
    mount Blazer::Engine, at: "blazer"
    mount RailsPerformance::Engine, at: "rails_performance"
    mount PgHero::Engine, at: "pghero"
  end

  ### All visitors
  get "/terms", to: "pages#terms"
  get "/privacy", to: "pages#privacy"
  get "/about", to: "pages#about"

  root to: "pages#home"

  ### Errors
  match "/404", to: "errors#not_found", via: :all
  match "/406", to: "errors#unacceptable", via: :all
  match "/422", to: "errors#unprocessable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  ### Developer tools
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
    mount Lookbook::Engine, at: "/lookbook"
  end
end

app/models/user.rb
class User < ApplicationRecord
  include PgSearch::Model
  include Discard::Model
  include IdentityCache

  OAUTH_PROVIDERS = %w[google].freeze

  devise :database_authenticatable, :registerable,
    :confirmable, :lockable, :timeoutable, :trackable,
    :recoverable, :rememberable, :trackable, :validatable,
    :pwned_password, :omniauthable, omniauth_providers: OAUTH_PROVIDERS

  rolify
  has_subscriptions

  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_fit: [150, 150]
    attachable.variant :medium, resize_to_fit: [300, 300]
    attachable.variant :large, resize_to_fit: [500, 500]
  end

  enum gender: {
    male: "male",
    female: "female",
    other: "other",
    not_specified: "not_specified"
  }

  has_many :identities, dependent: :destroy
  belongs_to :banned_by, class_name: "User", optional: true
  has_many :login_activities, as: :user
  has_many :ahoy_visits, class_name: "Ahoy::Visit"
  has_many :ahoy_events, class_name: "Ahoy::Event"
  has_many :notifications, as: :recipient

  validates :first_name, presence: true, on: :update
  validates :last_name, presence: true, on: :update
  validates :time_zone, presence: true
  validate :check_name_format, on: :create
  validates :avatar, content_type: %w[image/png image/jpg image/jpeg]

  before_destroy :delete_avatar

  # discard
  after_discard do
    identities.discard_all
    login_activities.discard_all
    ahoy_visits.discard_all
    ahoy_events.discard_all
    notifications.discard_all
  end

  after_undiscard do
    identities.undiscard_all
    login_activities.undiscard_all
    ahoy_visits.undiscard_all
    ahoy_events.undiscard_all
    notifications.undiscard_all
  end

  ### Avatar
  def delete_avatar
    avatar&.purge_later
  end

  ### Search
  pg_search_scope :search,
    against: %i[first_name last_name email],
    using: {
      tsearch: {prefix: true},
      trigram: {}
    }

  # scopes
  default_scope { kept.order(created_at: :asc) }

  ### Devise async
  def send_devise_notification(notification, *args)
    if Rails.env.production? || Rails.env.staging?
      devise_mailer.send(notification, self, *args).deliver_later
    else
      devise_mailer.send(notification, self, *args).deliver_now
    end
  end

  ### Ban
  def account_active?
    banned_at.nil?
  end

  def active_for_authentication?
    super && account_active?
  end

  def inactive_message
    # i18n-tasks-use t('devise.failure.banned')
    account_active? ? super : :banned
  end

  ### Name
  def name=(full_name)
    self.first_name, self.last_name = full_name.to_s.squish.split(/\s/, 2)
  end

  def name
    [first_name, last_name].join(" ")
  end

  alias_method :full_name, :name

  def familiar_name
    last_name.present? ? "#{first_name} #{last_name.first}." : first_name
  end

  def abbreviated_name
    last_name.present? ? "#{first_name.first}. #{last_name}" : first_name
  end

  def sorted_name
    last_name.present? ? "#{last_name}, #{first_name.first}" : first_name
  end

  def initials
    name.remove(/(\(|\[).*(\)|\])/).scan(/([[:word:]])[[:word:]]*/i).join
  end

  def check_name_format
    errors.add(:name, I18n.t("activerecord.errors.messages.wrong_name_format")) unless name.match? /^\S+\s\S+$/
  end

  def to_s
    name
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: %i[show edit update destroy impersonate]
  skip_before_action :check_admin, only: :stop_impersonating

  def index
    if params[:query].blank?
      @pagy, @users = pagy(User.order("created_at DESC"))
    else
      logger.debug("Search query: #{params[:query]}")
      @pagy, @users = pagy(User.search(params[:query]).order("created_at DESC"))
    end
  end

  def show
    @roles = @user.roles.includes([:resource]).order("created_at DESC")
    @login_activities = @user.login_activities.last(10)
  end

  def edit
  end

  def update
    @user.skip_reconfirmation!
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to [:admin, @user], notice: "User info updated" }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.discard
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: "User deleted", status: :see_other }
      format.json { head :no_content }
    end
  end

  def impersonate
    impersonate_user(@user)
    redirect_to root_path
  end

  def stop_impersonating
    stop_impersonating_user
    redirect_to root_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :name, :gender, :birthday, :avatar, :time_zone)
  end
end

app/controllers/users/base_controller.rb
class Users::BaseController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized
end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      raise e if get?

      if has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users/identities_controller.rb
class Users::IdentitiesController < Users::BaseController
  before_action :set_identity, only: %i[destroy]

  def destroy
    authorize %i[users identities], :destroy?
    ahoy.track "Destroy identity", identity: @identity.provider
    @identity.destroy!
    redirect_back fallback_location: root_url
  end

  private

  def identity_params
    params.permit(:provider)
  end

  def set_identity
    @identity = current_user.identities.find_by(provider: params[:provider])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include Utmable

  before_action :set_identity
  before_action :set_user

  attr_reader :identity, :user

  def google
    handle_auth "Google"
  end

  private

  def handle_auth(kind)
    if identity.present?
      identity.update(identity_attrs)
    else
      user.identities.create(identity_attrs)
    end

    if signed_in?
      redirect_to root_path
    else
      sign_in_and_redirect user, event: :authentication
      set_flash_message :notice, :success, kind: kind
    end
  end

  def auth
    request.env["omniauth.auth"]
  end

  def set_identity
    @identity = Identity.where(provider: auth.provider, uid: auth.uid).first
  end

  def set_user
    @user = if signed_in?
      current_user
    elsif identity.present?
      identity.user
    else
      User.find_or_create_by(email: auth.info.email) do |u|
        u.name = auth.info.name
        u.password = Devise.friendly_token[0, 20]
        u.time_zone = browser_time_zone&.name || Time.zone.name

        utm_resource u
        utm_clear_cookies
        
        u.skip_confirmation!
      end
    end
    CreateAvatarJob.perform_now(@user) unless @user.avatar.present?
  end

  def identity_attrs
    {
      provider: auth.provider,
      uid: auth.uid
    }
  end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < Users::BaseController
  def edit
    authorize %i[users profile], :edit?
    ahoy.track "Edit profile"
  end

  def update
    user = current_user
    authorize %i[users profile], :update?

    respond_to do |format|
      if user.update(profile_params)
        ahoy.track "Update user profile"
        format.html { redirect_to edit_profile_path, notice: t(".action_successful") }
        format.json { render :show, status: :ok, location: user }
      else
        ahoy.track "Update user profile failed"
        format.html {
          flash.now[:alert] = t(".action_failed")
          render :edit, status: :unprocessable_entity
        }
        format.json { render json: user.errors, status: :unprocessable_entity }
      end
    end
  end

  def profile_params
    params.require(:user).permit(:first_name, :last_name, :gender, :birthday, :avatar, :time_zone)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include Utmable

  layout "application", only: :edit

  def build_resource(hash = {})
    super
    CreateAvatarJob.perform_now(resource) unless resource.avatar.present?
    resource.time_zone = browser_time_zone&.name || Time.zone.name
    utm_resource resource
  end

  def create
    super
    utm_clear_cookies
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def respond_to_on_destroy
    respond_to do |format|
      format.all { head :no_content }
      format.any(*navigational_formats) { redirect_to after_sign_out_path_for(resource_name), status: :see_other }
    end
  end
end

app/views/admin/users/_search_form.html.erb
<%= form_with(local: true, method: :get, url: { action: "index" }, class: "my-3 row justify-content-between") do |form| %>
  <div class="col-10">
    <%= form.text_field :query, value: params[:query].presence && params[:query], placeholder: 'Search users', class: "form-control" %>
  </div>
  <div class="col-2">
    <%= form.submit "Search", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<tr id="<%= dom_id(user) %>">
  <td>
    <%= link_to [:admin, user] do %>
      <%= user.name %>
    <% end %>
  </td>
  <td><%= user.email %></td>
  <td><%= local_time_ago(user.created_at) %></td>
  <td>
    <% unless user == current_user %>
      <%= link_to "Login As", impersonate_admin_user_path(user), data: {turbo_method: :post}, class: "btn btn-secondary" %>
      <%= link_to "Edit", edit_admin_user_path(user), class: "btn btn-secondary" %>
      <%= link_to "Delete", [:admin, user], data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger" %>
    <% end %>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<p>Find me in app/views/admin/users/edit.html.erb</p>

app/views/admin/users/index.html.erb
<% breadcrumb :admin_users %>

<h1>Manage users</h1>

<%= render 'admin/users/search_form' %>

<div>
  <table class="table">
    <thead class="table-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Registered at</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody id="users">
    <%= render @users %>
    </tbody>
  </table>
</div>

<%== pagy_bootstrap_nav(@pagy) %>

app/views/admin/users/show.html.erb
<% breadcrumb :admin_user, @user %>

<div class="flex flex-auto gap-3 justify-start">
  <div class="mt-5">
    <%= render (Elements::AvatarComponent.new(user: @user, preset: :medium)) %>

    <div class="mt-5">
      <h5><%= @user.name %></h5>
      <p><%= @user.email %></p>
      <p>Sex: <%= @user.gender %></p>
      <p>Birthday: <%= @user.birthday %></p>
      <p>Timezone: <%= @user.time_zone %></p>
    </div>

    <% unless @user == current_user %>
      <div class="mt-5">
        <%= link_to "Edit", edit_admin_user_path(@user) %>
        <%= link_to "Delete", [:admin, @user], data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
      </div>
    <% end %>
  </div>

  <div class="grow">
    <h3 class="mt-3">User info</h3>
    <table>
      <tr>
        <td>Confirmed at</td>
        <td><%= @user.confirmed_at %></td>
      </tr>
      <tr>
        <td>Confirmation sent at</td>
        <td><%= @user.confirmation_sent_at %></td>
      </tr>
      <tr>
        <td>Unconfirmed email</td>
        <td><%= @user.unconfirmed_email %></td>
      </tr>
      <tr>
        <td>Sign in count</td>
        <td><%= @user.sign_in_count %></td>
      </tr>
      <tr>
        <td>Current signed in at</td>
        <td><%= @user.current_sign_in_at %></td>
      </tr>
      <tr>
        <td>Current signed in ip address</td>
        <td><%= @user.current_sign_in_ip %></td>
      </tr>
      <tr>
        <td>Last signed in at</td>
        <td><%= @user.last_sign_in_at %></td>
      </tr>
      <tr>
        <td>Last signed in ip address</td>
        <td><%= @user.last_sign_in_ip %></td>
      </tr>
      <tr>
        <td>Failed login attempts</td>
        <td><%= @user.failed_attempts %></td>
      </tr>
      <tr>
        <td>Locked at</td>
        <td><%= @user.locked_at %></td>
      </tr>
    </table>

    <h3 class="mt-3">Acquisition info</h3>
    <table>
      <tr>
        <td>UTM Source</td>
        <td><%= @user.utm_source %></td>
      </tr>
      <tr>
        <td>UTM Medium</td>
        <td><%= @user.utm_medium %></td>
      </tr>
      <tr>
        <td>UTM Campaign</td>
        <td><%= @user.utm_campaign %></td>
      </tr>
      <tr>
        <td>UTM Term</td>
        <td><%= @user.utm_term %></td>
      </tr>
      <tr>
        <td>UTM Content</td>
        <td><%= @user.utm_content %></td>
      </tr>
      <tr>
        <td>Gclid</td>
        <td><%= @user.gclid %></td>
      </tr>
      <tr>
        <td>Ysclid</td>
        <td><%= @user.ysclid %></td>
      </tr>      
    </table>

    <div class="mt-5 w-full">
      <h3>Login activities (last 10)</h3>
      <table class="table">
        <thead class="table-dark">
        <tr>
          <th>Date and time</th>
          <th>IP</th>
          <th>User Agent</th>
          <th>Referrer</th>
        </tr>
        </thead>
        <tbody>
        <% @login_activities.each do |activity| %>
          <tr>
            <td><%= link_to l(activity.created_at, format: :long), admin_login_activity_path(activity) %></td>
            <td><%= activity.ip %></td>
            <td><%= activity.user_agent %></td>
            <td><%= activity.referrer %></td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <%= link_to "More logs", admin_user_login_activities_path(@user) %>

    </div>

    <div class="mt-5 w-full">
      <h3>Roles</h3>

      <%= form_with(model: nil, url: admin_user_add_role_path(@user), local: true, class: "my-5") do |f| %>

        <%= f.label 'Role name' %>
        <%= f.select :role_name, Role::ALLOWED_GLOBAL_ROLES, {},
                     { class: "w-1/4" } %>
        <%= f.submit 'Add', class: "btn btn-primary mt-3" %>
      <% end %>

      <table class="table">
        <thead class="table-dark">
        <tr>
          <th>Role</th>
          <th>Resource</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @roles.each do |role| %>
          <tr>
            <td><%= role.name.titleize %></td>
            <td><%= role.resource %></td>
            <td><%= link_to 'Remove role', admin_user_role_path(@user, role.name), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <div class="mt-5">
      <% unless @user == current_user %>
        <h3>Ban</h3>

        <% if @user.banned_at %>
          <table>
            <tr>
              <td>Banned at</td>
              <td><%= @user.banned_at %></td>
            </tr>
            <tr>
              <td>Ban reason</td>
              <td><%= @user.ban_reason %></td>
            </tr>
          </table>

          <%= link_to "Unban", admin_user_remove_ban_path(@user), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-danger" %>

        <% else %>
          <%= form_with(url: admin_user_create_ban_path(user_id: @user.id), method: :post, local: true) do |f| %>
            <%= f.label 'Ban reason' %>
            <%= f.text_area :ban_reason, placeholder: "Add ban", class: "w-full h-20" %>
            <%= f.submit class: "btn btn-danger mt-3" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

</div>