config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations",
                           sessions: "users/sessions"}

  ### Registered users
  authenticated :user do
    root to: "customer/dashboard#index", as: :authenticated_root
  end
  
  scope :users, module: "users" do
    resource :profiles, only: %i[edit update], as: :profile
    delete "identities", to: "identities#destroy"
  end

  ### Admins
  namespace :admin do
    get "/", to: "dashboard#index", as: :dashboard

    resources :users, except: [:new, :create] do
      # roles
      delete "/roles/:role_name", to: "roles#destroy", as: :role
      post "/roles/", to: "roles#create", as: :add_role

      # bans
      post "/ban", to: "bans#create", as: :create_ban
      delete "/ban", to: "bans#destroy", as: :remove_ban

      # pretending
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection

      resources :login_activities, only: [:index, :show], shallow: true
    end
  end

  authenticate :user, ->(u) { u.is_admin? } do
    mount GoodJob::Engine, at: "good_job"
    mount Blazer::Engine, at: "blazer"
    mount RailsPerformance::Engine, at: "rails_performance"
    mount PgHero::Engine, at: "pghero"
  end

  ### All visitors
  get "/terms", to: "pages#terms"
  get "/privacy", to: "pages#privacy"
  get "/about", to: "pages#about"

  root to: "pages#home"

  ### Errors
  match "/404", to: "errors#not_found", via: :all
  match "/406", to: "errors#unacceptable", via: :all
  match "/422", to: "errors#unprocessable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  ### Developer tools
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
    mount Lookbook::Engine, at: "/lookbook"
  end
end

app/views/layouts/_admin_navigation.html.erb
<nav>
  <ul class="my-3 nav flex-column">
    <li>
      <%= active_link_to "Dashboard", admin_dashboard_path %>
    </li>
    <li>
      <%= active_link_to "Users management", admin_users_path %>
    </li>
  </ul>
</nav>

<nav>
  <ul class="my-3 nav flex-column">
    <li>
      <%= link_to "Good Job", good_job_path %>
    </li>
    <li>
      <%= link_to "Blazer", blazer_path %>
    </li>
    <li>
      <%= link_to "Performance", rails_performance_path %>
    </li>
    <li>
      <%= link_to "Pg Hero", pg_hero_path %>
    </li>
  </ul>
</nav>

<% if Rails.env.development? %>
  <nav>
    <ul class="my-3 nav flex-column">
      <li>
        <%= link_to "Lookbook", lookbook_path %>
      </li>
      <li>
        <%= link_to "Letter opener", letter_opener_web_path %>
      </li>
    </ul>
  </nav>
<% end %>

app/views/layouts/_flash.html.erb
<% unless flash.empty? %>
  <% flash.each do |key, value| %>
    <% next unless value.is_a? String %>
    <div class="<%= flash_class(key) %> mt-2">
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container text-center">
  <ul class="list-inline">
    <li class="list-inline-item">
    (c) <%= Date.today.year %>
  </li>

  <li class="list-inline-item">
    <%= link_to t(:"navigation.privacy_page"), privacy_path %>
  </li>

  <li class="list-inline-item">
    <%= link_to t(:"navigation.terms_page"), terms_path %>
  </li>
  
  <li>
    <%= link_to t(:"navigation.about_page"), about_path %>
  </li>    
</ul>  
</div>

<%= render "layouts/locale_switch" %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "APP_NAME", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-1" id="navbarNav">
      <ul class="mb-2 navbar-nav me-auto mb-lg-0">
        <li class="nav-item">
          <%= active_link_to signed_in? ? "Dashboard" : "Home", root_path, class: "nav-link", active: :exclusive %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto flex-nowrap">
        <% if signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="navbarDarkDropdownMenuLink">
              <% if current_user.is_admin? %>
                <li>
                  <%= active_link_to "Admin console", admin_dashboard_path, class: "dropdown-item" %>
                </li>
              <% end %>
              <li>
                <%= active_link_to t('navigation.profile'), edit_profile_path, class: "dropdown-item" %>
              </li>
              <li>
                <%= active_link_to t('navigation.account'), edit_user_registration_path, class: "dropdown-item" %>
              </li>
              <% if current_user != true_user %>
                <li><%= link_to "Back to admin", stop_impersonating_admin_users_path, data: { turbo_method: :post }, class: "dropdown-item" %></li>
                </ul>
              <% else %>
                <li><%= link_to t('navigation.sign_out'), destroy_user_session_path, id: "sign_out_link",  data: { turbo_method: :delete }, class: "dropdown-item" %></li>
                </ul>
              <% end %>
        <% else %>
          <li class="nav-item me-2">
            <%= link_to t('navigation.sign_up'), new_user_registration_path, id: "sign_up_link", class: 'btn btn-primary' %>
          </li>
          <li class="nav-item me-2">
            <%= link_to t('navigation.sign_in'), new_user_session_path, id: "sign_in_link", class: 'btn btn-secondary' %>
          </li>
        <% end %>
        <% if Rails.env.development? %>
          <li>
            <%= link_to "Letter Opener console", letter_opener_web_path, target: "_blank", rel: "nofollow", class: 'btn btn-secondary' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_locale_switch.html.erb
<div class="container text-center">
  <ul class="list-inline">
    <li class="list-inline-item">
      <%= t("application.available_locales_label") %>
    </li>
    <% I18n.available_locales.each do |locale| %>
      <li class="list-inline-item">
        <% if cookies[:locale].present? %>
          <%= link_to locale, url_for(locale: locale), class: "#{'active' if locale.to_s == cookies[:locale]}" %>
        <% else %>
          <%= link_to locale, url_for(locale: locale), class: "#{'active' if locale.to_s == I18n.default_locale.to_s}" %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/admin.html.erb
<!doctype html>
<html lang="<%= I18n.locale.to_s %>">
  <head>
    <title>APP_NAME Admin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body>
    <header>
      <base href="<%= Rails.configuration.settings.base_url %>">
      <%= render "layouts/header" %>
    </header>
    <main class="container">
      <div class="my-3">
        <%= breadcrumbs style: :bootstrap5, display_single_fragment: true %>
      </div>

      <%= render Elements::FlashComponent.new %>
      
      <div class="row">
        <div class="col-2">
          <%= render "layouts/admin_navigation" %>         
        </div>
        <div class="col">
          <%= yield %>          
        </div>        
      </div>

    </main>
    <footer>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="<%= I18n.locale.to_s %>">
  <head>
    <base href="<%= Rails.configuration.settings.base_url %>">
    <%= display_meta_tags site: "APP_NAME", og: {
      title: :title,
      site_name: :site,
    } %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <main class="container">
      <div class="my-3">
        <%= breadcrumbs style: :bootstrap5, display_single_fragment: true %>
      </div>

      <%= render Elements::FlashComponent.new %>
      
      <%= yield %>
    </main>
    <footer>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>

app/views/layouts/component_preview.html.erb
<!doctype html>
<html lang="<%= I18n.locale.to_s %>">
<head>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body>
  <main>
    <%= yield %>
  </main>
</body>
</html>

app/views/layouts/devise.html.erb
<!doctype html>
<html lang="<%= I18n.locale.to_s %>">
  <head>
    <base href="<%= Rails.configuration.settings.base_url %>">
    <%= display_meta_tags site: "APP_NAME", og: {
      title: :title,
      site_name: :site,
    } %>
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body data-turbo="false" class="text-center">
    <header></header>
    <main>
        <%= render Elements::FlashComponent.new %>
        <%= yield %>
    </main>
    <footer></footer>
  </body>
</html>